// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/change_data_capture.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LitetableOperation is an enum that describes the type of operations that trigger CDC events.
// Create operations are generally attached to database configuration and do not affect any indexed
// data.
type LitetableOperation int32

const (
	LitetableOperation_READ   LitetableOperation = 0
	LitetableOperation_WRITE  LitetableOperation = 1
	LitetableOperation_DELETE LitetableOperation = 2
)

// Enum value maps for LitetableOperation.
var (
	LitetableOperation_name = map[int32]string{
		0: "READ",
		1: "WRITE",
		2: "DELETE",
	}
	LitetableOperation_value = map[string]int32{
		"READ":   0,
		"WRITE":  1,
		"DELETE": 2,
	}
)

func (x LitetableOperation) Enum() *LitetableOperation {
	p := new(LitetableOperation)
	*p = x
	return p
}

func (x LitetableOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LitetableOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_change_data_capture_proto_enumTypes[0].Descriptor()
}

func (LitetableOperation) Type() protoreflect.EnumType {
	return &file_proto_change_data_capture_proto_enumTypes[0]
}

func (x LitetableOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LitetableOperation.Descriptor instead.
func (LitetableOperation) EnumDescriptor() ([]byte, []int) {
	return file_proto_change_data_capture_proto_rawDescGZIP(), []int{0}
}

type CDCSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *CDCSubscriptionRequest) Reset() {
	*x = CDCSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_change_data_capture_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CDCSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDCSubscriptionRequest) ProtoMessage() {}

func (x *CDCSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_data_capture_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDCSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CDCSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_change_data_capture_proto_rawDescGZIP(), []int{0}
}

func (x *CDCSubscriptionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// CDCEvent represents a view of the data that is changing in a Litetable column qualifier.
// It represents the entire change, not the latest value.
type CDCEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// operation describes the type of change that occurred. Not all operations create a CDC event.
	Operation LitetableOperation `protobuf:"varint,1,opt,name=operation,proto3,enum=litetable.cdc.v1.LitetableOperation" json:"operation,omitempty"`
	// row_key is the primary index in a Litetable row.
	RowKey string `protobuf:"bytes,2,opt,name=row_key,json=rowKey,proto3" json:"row_key,omitempty"`
	// family is a configured family in the Litetable.
	Family string `protobuf:"bytes,3,opt,name=family,proto3" json:"family,omitempty"`
	// qualifier is a column qualifier, which contains an array of time series values.
	Qualifier string `protobuf:"bytes,4,opt,name=qualifier,proto3" json:"qualifier,omitempty"`
	// value is the value of the column qualifier. It is a byte array of whatever is saved.
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// timestamp_unix is the time in milliseconds since the epoch when the change occurred.
	TimestampUnix int64 `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	// tombstone is true if the value is a tombstone. A tombstone is a marker that indicates that
	// the value will be garbage collected in the future.
	Tombstone bool `protobuf:"varint,7,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	// expires_at_unix is the time in milliseconds since the epoch when the value will approximately be
	// garbage collected. This value will not be garbage collected before this time.
	ExpiresAtUnix int64 `protobuf:"varint,8,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
}

func (x *CDCEvent) Reset() {
	*x = CDCEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_change_data_capture_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CDCEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDCEvent) ProtoMessage() {}

func (x *CDCEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_change_data_capture_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDCEvent.ProtoReflect.Descriptor instead.
func (*CDCEvent) Descriptor() ([]byte, []int) {
	return file_proto_change_data_capture_proto_rawDescGZIP(), []int{1}
}

func (x *CDCEvent) GetOperation() LitetableOperation {
	if x != nil {
		return x.Operation
	}
	return LitetableOperation_READ
}

func (x *CDCEvent) GetRowKey() string {
	if x != nil {
		return x.RowKey
	}
	return ""
}

func (x *CDCEvent) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *CDCEvent) GetQualifier() string {
	if x != nil {
		return x.Qualifier
	}
	return ""
}

func (x *CDCEvent) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CDCEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *CDCEvent) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *CDCEvent) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

var File_proto_change_data_capture_proto protoreflect.FileDescriptor

var file_proto_change_data_capture_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x10, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x63, 0x64, 0x63,
	0x2e, 0x76, 0x31, 0x22, 0x35, 0x0a, 0x16, 0x43, 0x44, 0x43, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xa0, 0x02, 0x0a, 0x08, 0x43,
	0x44, 0x43, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6c, 0x69, 0x74,
	0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x63, 0x64, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x77, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x77, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e,
	0x69, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x6d, 0x62, 0x73,
	0x74, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x6f, 0x6d, 0x62,
	0x73, 0x74, 0x6f, 0x6e, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73,
	0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x2a, 0x35, 0x0a,
	0x12, 0x4c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x10, 0x02, 0x32, 0x61, 0x0a, 0x0a, 0x43, 0x44, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x53, 0x0a, 0x09, 0x43, 0x44, 0x43, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x28, 0x2e, 0x6c, 0x69, 0x74, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x63, 0x64, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x44, 0x43, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x69, 0x74, 0x65,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x63, 0x64, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x44, 0x43,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_change_data_capture_proto_rawDescOnce sync.Once
	file_proto_change_data_capture_proto_rawDescData = file_proto_change_data_capture_proto_rawDesc
)

func file_proto_change_data_capture_proto_rawDescGZIP() []byte {
	file_proto_change_data_capture_proto_rawDescOnce.Do(func() {
		file_proto_change_data_capture_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_change_data_capture_proto_rawDescData)
	})
	return file_proto_change_data_capture_proto_rawDescData
}

var file_proto_change_data_capture_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_change_data_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_change_data_capture_proto_goTypes = []interface{}{
	(LitetableOperation)(0),        // 0: litetable.cdc.v1.LitetableOperation
	(*CDCSubscriptionRequest)(nil), // 1: litetable.cdc.v1.CDCSubscriptionRequest
	(*CDCEvent)(nil),               // 2: litetable.cdc.v1.CDCEvent
}
var file_proto_change_data_capture_proto_depIdxs = []int32{
	0, // 0: litetable.cdc.v1.CDCEvent.operation:type_name -> litetable.cdc.v1.LitetableOperation
	1, // 1: litetable.cdc.v1.CDCService.CDCStream:input_type -> litetable.cdc.v1.CDCSubscriptionRequest
	2, // 2: litetable.cdc.v1.CDCService.CDCStream:output_type -> litetable.cdc.v1.CDCEvent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_change_data_capture_proto_init() }
func file_proto_change_data_capture_proto_init() {
	if File_proto_change_data_capture_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_change_data_capture_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CDCSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_change_data_capture_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CDCEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_change_data_capture_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_change_data_capture_proto_goTypes,
		DependencyIndexes: file_proto_change_data_capture_proto_depIdxs,
		EnumInfos:         file_proto_change_data_capture_proto_enumTypes,
		MessageInfos:      file_proto_change_data_capture_proto_msgTypes,
	}.Build()
	File_proto_change_data_capture_proto = out.File
	file_proto_change_data_capture_proto_rawDesc = nil
	file_proto_change_data_capture_proto_goTypes = nil
	file_proto_change_data_capture_proto_depIdxs = nil
}
